/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pharmacy.app.GUI.Sales;

import com.pharmacy.app.GUI.Authorization.*;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author phong
 */
public class HomeSales extends javax.swing.JPanel {

    /**
     * Creates new form AuthorizationManagement
     */
    public HomeSales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel19 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        cbxAll = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnAddMedicineToCart = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        pnCart = new javax.swing.JPanel();
        jSpinner1 = new javax.swing.JSpinner();
        jTextField8 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnDelete1LineInCart = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        lblPhoneCustomer = new javax.swing.JLabel();
        lblNameCustomer = new javax.swing.JLabel();
        lblPointCustomer = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        txtPhoneCustomer = new javax.swing.JTextField();
        txtNameCustomer = new javax.swing.JTextField();
        txtPointCustomer = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        lblTotalProductPrice = new javax.swing.JLabel();
        lblProductDiscount = new javax.swing.JLabel();
        lblVoucher = new javax.swing.JLabel();
        lblVoucherDiscount = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        txtTotalProductPrice = new javax.swing.JTextField();
        txtProductDiscoun = new javax.swing.JTextField();
        txtVoucher = new javax.swing.JTextField();
        txtVoucherDiscount = new javax.swing.JTextField();
        txtSubtotal = new javax.swing.JTextField();
        btnPayment = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        cbxAll1 = new javax.swing.JComboBox<>();
        txtSearch1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        lblPdf = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPromo1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(986, 578));
        setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1229, 800));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1050, 750));

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setPreferredSize(new java.awt.Dimension(1200, 750));
        jPanel19.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 500));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setMinimumSize(new java.awt.Dimension(400, 40));
        jPanel4.setPreferredSize(new java.awt.Dimension(800, 50));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 10));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(500, 40));
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        cbxAll.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxAll.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Active", "IsActive" }));
        cbxAll.setPreferredSize(new java.awt.Dimension(80, 35));
        jPanel8.add(cbxAll);

        txtSearch.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txtSearch.setText("Tìm kiếm thuốc");
        txtSearch.setMinimumSize(new java.awt.Dimension(80, 30));
        txtSearch.setPreferredSize(new java.awt.Dimension(400, 35));
        jPanel8.add(txtSearch);

        jPanel4.add(jPanel8);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 40));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnAddMedicineToCart.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAddMedicineToCart.setText("Thêm thuốc");
        btnAddMedicineToCart.setMargin(new java.awt.Insets(2, 10, 3, 10));
        btnAddMedicineToCart.setPreferredSize(new java.awt.Dimension(100, 35));
        btnAddMedicineToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMedicineToCartActionPerformed(evt);
            }
        });
        jPanel3.add(btnAddMedicineToCart);

        btnRefresh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.setPreferredSize(new java.awt.Dimension(80, 35));
        jPanel3.add(btnRefresh);

        jPanel4.add(jPanel3);

        jPanel1.add(jPanel4);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Danh sách thuốc");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel1.add(jLabel1);

        jScrollPane2.setMinimumSize(new java.awt.Dimension(760, 510));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(790, 250));

        tblProduct.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"123", "Parnadol", "vỉ", null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã thuốc", "Tên thuốc", "Đơn vị", "Đơn giá", "Tồn kho", "Hạn sử dụng", "Khuyến mãi (%)", "Tiền khuyến mãi", "Giá sau khuyến mãi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblProduct.setMaximumSize(new java.awt.Dimension(750, 600));
        tblProduct.setMinimumSize(new java.awt.Dimension(0, 0));
        tblProduct.setPreferredSize(new java.awt.Dimension(790, 250));
        tblProduct.setRowHeight(30);
        tblProduct.setShowGrid(true);
        tblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblProductMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblProduct);
        if (tblProduct.getColumnModel().getColumnCount() > 0) {
            tblProduct.getColumnModel().getColumn(0).setPreferredWidth(15);
            tblProduct.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblProduct.getColumnModel().getColumn(2).setPreferredWidth(10);
            tblProduct.getColumnModel().getColumn(3).setPreferredWidth(15);
            tblProduct.getColumnModel().getColumn(4).setPreferredWidth(10);
        }

        jPanel1.add(jScrollPane2);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Giỏ hàng");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setMaximumSize(new java.awt.Dimension(326589, 326589));
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 40));
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel2);

        pnCart.setBackground(new java.awt.Color(255, 255, 255));
        pnCart.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnCart.setPreferredSize(new java.awt.Dimension(790, 200));

        jTextField8.setText("Parnadol");

        javax.swing.GroupLayout pnCartLayout = new javax.swing.GroupLayout(pnCart);
        pnCart.setLayout(pnCartLayout);
        pnCartLayout.setHorizontalGroup(
            pnCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCartLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(588, Short.MAX_VALUE))
        );
        pnCartLayout.setVerticalGroup(
            pnCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCartLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        jPanel1.add(pnCart);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(750, 50));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 0));

        btnDelete1LineInCart.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDelete1LineInCart.setText("Xóa");
        btnDelete1LineInCart.setMaximumSize(new java.awt.Dimension(326589, 326589));
        btnDelete1LineInCart.setPreferredSize(new java.awt.Dimension(80, 30));
        jPanel5.add(btnDelete1LineInCart);

        btnReset.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReset.setText("Đặt lại");
        btnReset.setMaximumSize(new java.awt.Dimension(326589, 326589));
        btnReset.setPreferredSize(new java.awt.Dimension(80, 30));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel5.add(btnReset);

        jPanel1.add(jPanel5);

        jPanel19.add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(360, 700));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel6.setPreferredSize(new java.awt.Dimension(330, 170));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setPreferredSize(new java.awt.Dimension(160, 100));
        jPanel13.setLayout(new java.awt.GridLayout(3, 1, 0, 10));

        lblPhoneCustomer.setBackground(new java.awt.Color(255, 255, 255));
        lblPhoneCustomer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPhoneCustomer.setText("Số điện thoại ");
        lblPhoneCustomer.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel13.add(lblPhoneCustomer);

        lblNameCustomer.setBackground(new java.awt.Color(255, 255, 255));
        lblNameCustomer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNameCustomer.setText("Tên khách hàng");
        jPanel13.add(lblNameCustomer);

        lblPointCustomer.setBackground(new java.awt.Color(255, 255, 255));
        lblPointCustomer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPointCustomer.setText("Điểm tích lũy");
        jPanel13.add(lblPointCustomer);

        jPanel6.add(jPanel13);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setMinimumSize(new java.awt.Dimension(300, 350));
        jPanel12.setPreferredSize(new java.awt.Dimension(130, 100));
        jPanel12.setLayout(new java.awt.GridLayout(3, 1, 5, 10));

        txtPhoneCustomer.setPreferredSize(new java.awt.Dimension(200, 22));
        jPanel12.add(txtPhoneCustomer);

        txtNameCustomer.setEnabled(false);
        jPanel12.add(txtNameCustomer);

        txtPointCustomer.setEnabled(false);
        txtPointCustomer.setPreferredSize(new java.awt.Dimension(73, 25));
        jPanel12.add(txtPointCustomer);

        jPanel6.add(jPanel12);

        jPanel2.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thanh toán", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel7.setPreferredSize(new java.awt.Dimension(330, 270));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setPreferredSize(new java.awt.Dimension(160, 200));
        jPanel14.setLayout(new java.awt.GridLayout(6, 1, 0, 15));

        lblTotalProductPrice.setBackground(new java.awt.Color(255, 255, 255));
        lblTotalProductPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTotalProductPrice.setText("Tổng tiền sản phẩm");
        lblTotalProductPrice.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel14.add(lblTotalProductPrice);

        lblProductDiscount.setBackground(new java.awt.Color(255, 255, 255));
        lblProductDiscount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblProductDiscount.setText("Tiền giảm trên sản phẩm");
        jPanel14.add(lblProductDiscount);

        lblVoucher.setBackground(new java.awt.Color(255, 255, 255));
        lblVoucher.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblVoucher.setText("Voucher");
        jPanel14.add(lblVoucher);

        lblVoucherDiscount.setBackground(new java.awt.Color(255, 255, 255));
        lblVoucherDiscount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblVoucherDiscount.setText("Tiền giảm từ voucher");
        jPanel14.add(lblVoucherDiscount);

        lblSubtotal.setBackground(new java.awt.Color(255, 255, 255));
        lblSubtotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSubtotal.setText("Tạm tính");
        jPanel14.add(lblSubtotal);
        jPanel14.add(jLabel14);

        jPanel7.add(jPanel14);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setMinimumSize(new java.awt.Dimension(300, 350));
        jPanel15.setPreferredSize(new java.awt.Dimension(130, 200));
        jPanel15.setLayout(new java.awt.GridLayout(6, 1, 5, 10));

        txtTotalProductPrice.setEnabled(false);
        txtTotalProductPrice.setPreferredSize(new java.awt.Dimension(200, 22));
        jPanel15.add(txtTotalProductPrice);

        txtProductDiscoun.setEnabled(false);
        jPanel15.add(txtProductDiscoun);

        txtVoucher.setEnabled(false);
        txtVoucher.setPreferredSize(new java.awt.Dimension(73, 25));
        jPanel15.add(txtVoucher);

        txtVoucherDiscount.setEnabled(false);
        jPanel15.add(txtVoucherDiscount);

        txtSubtotal.setEnabled(false);
        jPanel15.add(txtSubtotal);

        btnPayment.setBackground(new java.awt.Color(0, 204, 51));
        btnPayment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPayment.setForeground(new java.awt.Color(255, 255, 255));
        btnPayment.setText("Thanh toán");
        btnPayment.setMargin(new java.awt.Insets(2, 10, 3, 10));
        btnPayment.setMaximumSize(new java.awt.Dimension(325689, 326589));
        btnPayment.setMinimumSize(new java.awt.Dimension(0, 0));
        btnPayment.setPreferredSize(new java.awt.Dimension(100, 40));
        btnPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPaymentMouseClicked(evt);
            }
        });
        btnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentActionPerformed(evt);
            }
        });
        jPanel15.add(btnPayment);

        jPanel7.add(jPanel15);

        jPanel2.add(jPanel7);

        jPanel19.add(jPanel2, java.awt.BorderLayout.EAST);

        jScrollPane1.setViewportView(jPanel19);

        jTabbedPane1.addTab("Bán hàng", jScrollPane1);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setMaximumSize(new java.awt.Dimension(326589, 326589));
        jPanel9.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel9.setPreferredSize(new java.awt.Dimension(1250, 750));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setMaximumSize(new java.awt.Dimension(800, 50));
        jPanel10.setMinimumSize(new java.awt.Dimension(800, 54));
        jPanel10.setPreferredSize(new java.awt.Dimension(1250, 70));

        cbxAll1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxAll1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Active", "IsActive" }));
        cbxAll1.setMinimumSize(new java.awt.Dimension(75, 25));
        cbxAll1.setPreferredSize(new java.awt.Dimension(80, 35));
        jPanel10.add(cbxAll1);

        txtSearch1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch1.setText("Search");
        txtSearch1.setMinimumSize(new java.awt.Dimension(80, 30));
        txtSearch1.setPreferredSize(new java.awt.Dimension(500, 35));
        jPanel10.add(txtSearch1);

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setText("Refresh");
        jButton4.setMaximumSize(new java.awt.Dimension(325689, 326589));
        jButton4.setMinimumSize(new java.awt.Dimension(0, 0));
        jButton4.setPreferredSize(new java.awt.Dimension(80, 35));
        jPanel10.add(jButton4);

        lblPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pdf.png"))); // NOI18N
        lblPdf.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel10.add(lblPdf);

        jPanel9.add(jPanel10, java.awt.BorderLayout.NORTH);

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setMinimumSize(new java.awt.Dimension(800, 550));
        jPanel18.setPreferredSize(new java.awt.Dimension(1250, 550));
        jPanel18.setLayout(new java.awt.BorderLayout());

        jScrollPane3.setMinimumSize(new java.awt.Dimension(0, 0));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(1210, 600));

        tblPromo1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblPromo1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"HD01", "Nguyen Van B", null, "101000"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Họ tên khách hàng", "Ngày mua", "Tổng tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblPromo1.setMaximumSize(new java.awt.Dimension(325689, 326589));
        tblPromo1.setMinimumSize(new java.awt.Dimension(0, 0));
        tblPromo1.setPreferredSize(new java.awt.Dimension(750, 700));
        tblPromo1.setRowHeight(30);
        tblPromo1.setShowGrid(true);
        tblPromo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblPromo1MousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(tblPromo1);
        tblPromo1.getAccessibleContext().setAccessibleDescription("");

        jPanel18.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel18, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Hóa đơn", jPanel9);

        add(jTabbedPane1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void tblProductMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblProductMousePressed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnPaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaymentMouseClicked

    }//GEN-LAST:event_btnPaymentMouseClicked

    private void btnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentActionPerformed
        PaymentDialog dialog = new PaymentDialog((JFrame) SwingUtilities.getWindowAncestor(this), true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnPaymentActionPerformed

    private void tblPromo1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPromo1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPromo1MousePressed

    private void btnAddMedicineToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMedicineToCartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddMedicineToCartActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMedicineToCart;
    private javax.swing.JButton btnDelete1LineInCart;
    private javax.swing.JButton btnPayment;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cbxAll;
    private javax.swing.JComboBox<String> cbxAll1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel lblNameCustomer;
    private javax.swing.JLabel lblPdf;
    private javax.swing.JLabel lblPhoneCustomer;
    private javax.swing.JLabel lblPointCustomer;
    private javax.swing.JLabel lblProductDiscount;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTotalProductPrice;
    private javax.swing.JLabel lblVoucher;
    private javax.swing.JLabel lblVoucherDiscount;
    private javax.swing.JPanel pnCart;
    private javax.swing.JTable tblProduct;
    private javax.swing.JTable tblPromo1;
    private javax.swing.JTextField txtNameCustomer;
    private javax.swing.JTextField txtPhoneCustomer;
    private javax.swing.JTextField txtPointCustomer;
    private javax.swing.JTextField txtProductDiscoun;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSearch1;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTotalProductPrice;
    private javax.swing.JTextField txtVoucher;
    private javax.swing.JTextField txtVoucherDiscount;
    // End of variables declaration//GEN-END:variables
}
