/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.pharmacy.app.GUI.Customer;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
/**
 *
 * @author BOI QUAN
 */
public class CustomerDetail extends javax.swing.JDialog {

    /**
     * Creates new form ChiTietCustomer
     */
    public CustomerDetail(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        centerTableCells();
        
    }

    private void centerTableCells(){
        DefaultTableCellRenderer centerRender = new DefaultTableCellRenderer();
        centerRender.setHorizontalAlignment(SwingConstants.CENTER);
        tbHistory.setDefaultRenderer(Object.class, centerRender);

        for (int i=0; i< tbHistory.getColumnCount();i++){
            tbHistory.getColumnModel().getColumn(i).setCellRenderer(centerRender);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plHeader = new javax.swing.JPanel();
        plInformation = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblPoint = new javax.swing.JLabel();
        txtPoint = new javax.swing.JTextField();
        plButton = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        plHistory = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHistory = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(800, 580));
        setPreferredSize(new java.awt.Dimension(1020, 650));
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        plHeader.setBackground(new java.awt.Color(255, 255, 255));
        plHeader.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "THÔNG TIN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        plHeader.setMaximumSize(new java.awt.Dimension(326589, 326589));
        plHeader.setMinimumSize(new java.awt.Dimension(800, 70));
        plHeader.setPreferredSize(new java.awt.Dimension(1000, 100));
        plHeader.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        plInformation.setBackground(new java.awt.Color(255, 255, 255));
        plInformation.setMaximumSize(new java.awt.Dimension(326589, 326589));
        plInformation.setMinimumSize(new java.awt.Dimension(0, 40));
        plInformation.setPreferredSize(new java.awt.Dimension(600, 50));

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblName.setText("Họ và Tên:");
        lblName.setMaximumSize(new java.awt.Dimension(326589, 326589));
        lblName.setMinimumSize(new java.awt.Dimension(70, 30));
        lblName.setPreferredSize(new java.awt.Dimension(100, 30));
        plInformation.add(lblName);

        txtName.setEditable(false);
        txtName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtName.setText("Nguyễn Văn A");
        txtName.setToolTipText("");
        txtName.setBorder(null);
        txtName.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtName.setEnabled(false);
        txtName.setFocusable(false);
        txtName.setMaximumSize(new java.awt.Dimension(100, 30));
        txtName.setMinimumSize(new java.awt.Dimension(100, 30));
        txtName.setPreferredSize(new java.awt.Dimension(100, 35));
        txtName.setSelectionColor(new java.awt.Color(255, 255, 255));
        plInformation.add(txtName);

        lblPhone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPhone.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPhone.setText("Số điện thoại:");
        lblPhone.setMaximumSize(new java.awt.Dimension(100, 30));
        lblPhone.setMinimumSize(new java.awt.Dimension(100, 30));
        lblPhone.setPreferredSize(new java.awt.Dimension(100, 30));
        plInformation.add(lblPhone);

        txtPhone.setEditable(false);
        txtPhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPhone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPhone.setText("0123456789");
        txtPhone.setBorder(null);
        txtPhone.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPhone.setEnabled(false);
        txtPhone.setFocusable(false);
        txtPhone.setMaximumSize(new java.awt.Dimension(100, 30));
        txtPhone.setMinimumSize(new java.awt.Dimension(100, 30));
        txtPhone.setPreferredSize(new java.awt.Dimension(100, 35));
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        plInformation.add(txtPhone);

        lblPoint.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPoint.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPoint.setText("Điểm:");
        lblPoint.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblPoint.setMaximumSize(new java.awt.Dimension(70, 30));
        lblPoint.setMinimumSize(new java.awt.Dimension(70, 30));
        lblPoint.setPreferredSize(new java.awt.Dimension(70, 30));
        plInformation.add(lblPoint);

        txtPoint.setEditable(false);
        txtPoint.setBackground(new java.awt.Color(255, 255, 255));
        txtPoint.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPoint.setText("100");
        txtPoint.setBorder(null);
        txtPoint.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPoint.setEnabled(false);
        txtPoint.setMargin(new java.awt.Insets(2, 15, 2, 6));
        txtPoint.setMaximumSize(new java.awt.Dimension(60, 30));
        txtPoint.setMinimumSize(new java.awt.Dimension(60, 30));
        txtPoint.setPreferredSize(new java.awt.Dimension(60, 35));
        plInformation.add(txtPoint);

        plHeader.add(plInformation);

        plButton.setBackground(new java.awt.Color(255, 255, 255));
        plButton.setMaximumSize(new java.awt.Dimension(326589, 326589));
        plButton.setMinimumSize(new java.awt.Dimension(200, 40));
        plButton.setPreferredSize(new java.awt.Dimension(350, 50));
        plButton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        btnUpdate.setBackground(new java.awt.Color(0, 204, 51));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Cập nhật");
        btnUpdate.setMaximumSize(new java.awt.Dimension(326589, 326589));
        btnUpdate.setMinimumSize(new java.awt.Dimension(77, 30));
        btnUpdate.setPreferredSize(new java.awt.Dimension(100, 35));
        plButton.add(btnUpdate);

        btnDelete.setBackground(new java.awt.Color(255, 0, 0));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Xóa");
        btnDelete.setMaximumSize(new java.awt.Dimension(72, 30));
        btnDelete.setMinimumSize(new java.awt.Dimension(72, 30));
        btnDelete.setPreferredSize(new java.awt.Dimension(72, 35));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        plButton.add(btnDelete);

        btnExit.setBackground(new java.awt.Color(153, 153, 153));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Thoát");
        btnExit.setPreferredSize(new java.awt.Dimension(80, 35));
        plButton.add(btnExit);

        plHeader.add(plButton);

        getContentPane().add(plHeader);

        plHistory.setBackground(new java.awt.Color(255, 255, 255));
        plHistory.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LỊCH SỬ MUA HÀNG", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        plHistory.setMaximumSize(new java.awt.Dimension(326589, 326589));
        plHistory.setMinimumSize(new java.awt.Dimension(800, 440));
        plHistory.setPreferredSize(new java.awt.Dimension(1000, 450));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setMaximumSize(new java.awt.Dimension(326589, 326589));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(780, 400));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(980, 400));

        tbHistory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"HD01", "03/02/2023", "NV01", null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Mã NV", "Tổng tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbHistory.setMaximumSize(new java.awt.Dimension(326589, 326589));
        tbHistory.setMinimumSize(new java.awt.Dimension(780, 80));
        tbHistory.setPreferredSize(new java.awt.Dimension(980, 450));
        tbHistory.setRowHeight(30);
        tbHistory.setShowGrid(true);
        jScrollPane1.setViewportView(tbHistory);
        if (tbHistory.getColumnModel().getColumnCount() > 0) {
            tbHistory.getColumnModel().getColumn(0).setHeaderValue("ID");
            tbHistory.getColumnModel().getColumn(1).setHeaderValue("Date");
            tbHistory.getColumnModel().getColumn(2).setHeaderValue("Mã NV");
            tbHistory.getColumnModel().getColumn(3).setHeaderValue("Tổng tiền");
        }

        plHistory.add(jScrollPane1);

        getContentPane().add(plHistory);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CustomerDetail dialog = new CustomerDetail(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPoint;
    private javax.swing.JPanel plButton;
    private javax.swing.JPanel plHeader;
    private javax.swing.JPanel plHistory;
    private javax.swing.JPanel plInformation;
    private javax.swing.JTable tbHistory;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPoint;
    // End of variables declaration//GEN-END:variables
}
