/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.pharmacy.app.GUI.Customer;

import com.pharmacy.app.BUS.CustomerBUS;
import com.pharmacy.app.DTO.CustomerDTO;
import javax.swing.JOptionPane;

/**
 *
 * @author BOI QUAN
 */
public class UpdateCustomer extends javax.swing.JDialog {
    private CustomerDTO customerDTO;
    private CustomerBUS customerBUS;
    /**
     * Creates new form AddCustomer
     * @param parent
     * @param modal
     */
    public UpdateCustomer(java.awt.Frame parent, boolean modal, CustomerDTO customerDTO, CustomerBUS customerBUS) {
        super(parent, modal);
        initComponents();
        this.customerBUS = customerBUS;
        this.customerDTO = customerDTO;
        setData(customerDTO);
    }
    private void setData(CustomerDTO customer) {
        txtId.setText(customer.getId());
        txtName.setText(customer.getName());
        txtPhone.setText(customer.getPhone());
        txtPoint.setText(String.valueOf(customer.getPoint()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        plInformation = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        plLbl = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblPoint = new javax.swing.JLabel();
        plTxt = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtPoint = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        plButton = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        plTitle.setBackground(new java.awt.Color(255, 255, 255));
        plTitle.setMaximumSize(new java.awt.Dimension(326589, 326589));
        plTitle.setMinimumSize(new java.awt.Dimension(400, 50));
        plTitle.setPreferredSize(new java.awt.Dimension(450, 350));

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Cập nhật thông tin khách hàng");
        lblTitle.setMaximumSize(new java.awt.Dimension(326589, 326589));
        lblTitle.setMinimumSize(new java.awt.Dimension(400, 50));
        lblTitle.setPreferredSize(new java.awt.Dimension(450, 50));
        plTitle.add(lblTitle);

        plInformation.setBackground(new java.awt.Color(255, 255, 255));
        plInformation.setMaximumSize(new java.awt.Dimension(326589, 326589));
        plInformation.setMinimumSize(new java.awt.Dimension(400, 220));
        plInformation.setPreferredSize(new java.awt.Dimension(450, 300));
        plInformation.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setMaximumSize(new java.awt.Dimension(350, 5));
        jSeparator1.setMinimumSize(new java.awt.Dimension(350, 5));
        jSeparator1.setPreferredSize(new java.awt.Dimension(350, 5));
        plInformation.add(jSeparator1);

        plLbl.setBackground(new java.awt.Color(255, 255, 255));
        plLbl.setMaximumSize(new java.awt.Dimension(100, 100));
        plLbl.setMinimumSize(new java.awt.Dimension(100, 100));
        plLbl.setPreferredSize(new java.awt.Dimension(100, 160));
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10);
        flowLayout2.setAlignOnBaseline(true);
        plLbl.setLayout(flowLayout2);

        lblId.setBackground(new java.awt.Color(255, 255, 255));
        lblId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblId.setText("Mã khách hàng");
        lblId.setPreferredSize(new java.awt.Dimension(100, 30));
        plLbl.add(lblId);

        lblName.setBackground(new java.awt.Color(255, 255, 255));
        lblName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblName.setText("Họ và Tên");
        lblName.setMaximumSize(new java.awt.Dimension(326589, 326589));
        lblName.setMinimumSize(new java.awt.Dimension(80, 30));
        lblName.setPreferredSize(new java.awt.Dimension(100, 30));
        plLbl.add(lblName);

        lblPhone.setBackground(new java.awt.Color(255, 255, 255));
        lblPhone.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPhone.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPhone.setText("Số điện thoại");
        lblPhone.setMaximumSize(new java.awt.Dimension(326589, 326589));
        lblPhone.setMinimumSize(new java.awt.Dimension(80, 30));
        lblPhone.setPreferredSize(new java.awt.Dimension(100, 30));
        plLbl.add(lblPhone);

        lblPoint.setBackground(new java.awt.Color(255, 255, 255));
        lblPoint.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPoint.setText("Điểm");
        lblPoint.setPreferredSize(new java.awt.Dimension(100, 30));
        plLbl.add(lblPoint);

        plInformation.add(plLbl);

        plTxt.setBackground(new java.awt.Color(255, 255, 255));
        plTxt.setMaximumSize(new java.awt.Dimension(250, 100));
        plTxt.setMinimumSize(new java.awt.Dimension(250, 100));
        plTxt.setPreferredSize(new java.awt.Dimension(250, 160));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10);
        flowLayout1.setAlignOnBaseline(true);
        plTxt.setLayout(flowLayout1);

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(255, 255, 255));
        txtId.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtId.setFocusable(false);
        txtId.setPreferredSize(new java.awt.Dimension(220, 30));
        plTxt.add(txtId);

        txtName.setMaximumSize(new java.awt.Dimension(220, 30));
        txtName.setMinimumSize(new java.awt.Dimension(220, 30));
        txtName.setPreferredSize(new java.awt.Dimension(220, 30));
        plTxt.add(txtName);

        txtPhone.setMaximumSize(new java.awt.Dimension(220, 30));
        txtPhone.setMinimumSize(new java.awt.Dimension(220, 30));
        txtPhone.setPreferredSize(new java.awt.Dimension(220, 30));
        plTxt.add(txtPhone);

        txtPoint.setEditable(false);
        txtPoint.setBackground(new java.awt.Color(255, 255, 255));
        txtPoint.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtPoint.setFocusable(false);
        txtPoint.setPreferredSize(new java.awt.Dimension(220, 30));
        txtPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPointActionPerformed(evt);
            }
        });
        plTxt.add(txtPoint);

        plInformation.add(plTxt);

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setMaximumSize(new java.awt.Dimension(350, 5));
        jSeparator2.setMinimumSize(new java.awt.Dimension(350, 5));
        jSeparator2.setPreferredSize(new java.awt.Dimension(350, 5));
        plInformation.add(jSeparator2);

        plButton.setBackground(new java.awt.Color(255, 255, 255));
        plButton.setMaximumSize(new java.awt.Dimension(326589, 326589));
        plButton.setMinimumSize(new java.awt.Dimension(400, 50));
        plButton.setPreferredSize(new java.awt.Dimension(450, 50));
        plButton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        btnSave.setBackground(new java.awt.Color(0, 204, 51));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Lưu");
        btnSave.setMaximumSize(new java.awt.Dimension(70, 30));
        btnSave.setMinimumSize(new java.awt.Dimension(70, 30));
        btnSave.setPreferredSize(new java.awt.Dimension(70, 30));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        plButton.add(btnSave);

        btnCancel.setBackground(new java.awt.Color(153, 153, 153));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Hủy");
        btnCancel.setMaximumSize(new java.awt.Dimension(70, 30));
        btnCancel.setMinimumSize(new java.awt.Dimension(70, 30));
        btnCancel.setPreferredSize(new java.awt.Dimension(70, 30));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        plButton.add(btnCancel);

        plInformation.add(plButton);

        plTitle.add(plInformation);

        getContentPane().add(plTitle);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String id = txtId.getText();
        String name = txtName.getText();
        String phone = txtPhone.getText();
        String point = txtPoint.getText();
        CustomerDTO updateCustomer = new CustomerDTO();
        updateCustomer.setId(id);
        updateCustomer.setName(name);
        updateCustomer.setPhone(phone);

        boolean success = customerBUS.updateCustomer(updateCustomer);
        
        if (success){
            JOptionPane.showMessageDialog(this, "Cập nhật khách hàng thành công!");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Cập nhật khách hàng thất bại!");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPointActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPointActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            private CustomerDTO customerDTO;
            private CustomerBUS customerBUS;
            public void run() {
                UpdateCustomer dialog = new UpdateCustomer(new javax.swing.JFrame(), true, customerDTO, customerBUS);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPoint;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel plButton;
    private javax.swing.JPanel plInformation;
    private javax.swing.JPanel plLbl;
    private javax.swing.JPanel plTitle;
    private javax.swing.JPanel plTxt;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPoint;
    // End of variables declaration//GEN-END:variables
}
