/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pharmacy.app.GUI.Requests;

import com.pharmacy.app.GUI.Sales.PaymentDialog;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author phong
 */
public class EmployeeRequests extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeRequests
     */
    public EmployeeRequests() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRequest1 = new javax.swing.JPanel();
        txtSearchRequest = new javax.swing.JTextField();
        cbRequestType = new javax.swing.JComboBox<>();
        pnlRequestButton = new javax.swing.JPanel();
        btnAddRequest = new javax.swing.JButton();
        btnRefesh = new javax.swing.JButton();
        btnPdf = new javax.swing.JButton();
        pnlRequest2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequets = new javax.swing.JTable();

        pnlRequest1.setToolTipText("");
        pnlRequest1.setPreferredSize(new java.awt.Dimension(607, 40));
        pnlRequest1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        txtSearchRequest.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtSearchRequest.setForeground(new java.awt.Color(153, 153, 153));
        txtSearchRequest.setText("Tìm kiếm");
        txtSearchRequest.setHighlighter(null);
        txtSearchRequest.setMinimumSize(new java.awt.Dimension(250, 22));
        txtSearchRequest.setPreferredSize(new java.awt.Dimension(250, 22));
        txtSearchRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchRequestActionPerformed(evt);
            }
        });
        pnlRequest1.add(txtSearchRequest);

        cbRequestType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Chờ duyệt", "Đã duyệt", "Không duyệt" }));
        cbRequestType.setFocusable(false);
        cbRequestType.setMinimumSize(new java.awt.Dimension(80, 22));
        cbRequestType.setPreferredSize(new java.awt.Dimension(105, 22));
        cbRequestType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRequestTypeActionPerformed(evt);
            }
        });
        pnlRequest1.add(cbRequestType);

        pnlRequestButton.setPreferredSize(new java.awt.Dimension(300, 35));
        pnlRequestButton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 5));

        btnAddRequest.setText("Tạo");
        btnAddRequest.setFocusable(false);
        btnAddRequest.setMaximumSize(new java.awt.Dimension(72, 22));
        btnAddRequest.setMinimumSize(new java.awt.Dimension(72, 22));
        btnAddRequest.setPreferredSize(new java.awt.Dimension(72, 22));
        btnAddRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRequestActionPerformed(evt);
            }
        });
        pnlRequestButton.add(btnAddRequest);

        btnRefesh.setText("Tải lại");
        btnRefesh.setFocusable(false);
        btnRefesh.setMaximumSize(new java.awt.Dimension(72, 22));
        btnRefesh.setMinimumSize(new java.awt.Dimension(72, 22));
        btnRefesh.setPreferredSize(new java.awt.Dimension(72, 22));
        btnRefesh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefeshActionPerformed(evt);
            }
        });
        pnlRequestButton.add(btnRefesh);

        btnPdf.setText("In PDF");
        btnPdf.setFocusable(false);
        btnPdf.setMaximumSize(new java.awt.Dimension(72, 22));
        btnPdf.setMinimumSize(new java.awt.Dimension(72, 22));
        btnPdf.setPreferredSize(new java.awt.Dimension(72, 22));
        btnPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPdfActionPerformed(evt);
            }
        });
        pnlRequestButton.add(btnPdf);

        pnlRequest1.add(pnlRequestButton);

        pnlRequest2.setPreferredSize(new java.awt.Dimension(600, 439));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(670, 402));

        tblRequets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã đơn", "Ngày gửi đơn", "Loại đơn", "Trạng thái"
            }
        ));
        tblRequets.setFocusable(false);
        tblRequets.setMinimumSize(new java.awt.Dimension(500, 80));
        tblRequets.setPreferredSize(new java.awt.Dimension(500, 80));
        tblRequets.setShowGrid(true);
        jScrollPane1.setViewportView(tblRequets);

        pnlRequest2.add(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlRequest2, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                    .addComponent(pnlRequest1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnlRequest1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRequest2, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchRequestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchRequestActionPerformed

    private void cbRequestTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRequestTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRequestTypeActionPerformed

    private void btnAddRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRequestActionPerformed
        AddRequest addDialog = new AddRequest((JFrame) SwingUtilities.getWindowAncestor(this), true);
        addDialog.setLocationRelativeTo(null);
        addDialog.setVisible(true);
    }//GEN-LAST:event_btnAddRequestActionPerformed

    private void btnRefeshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefeshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefeshActionPerformed

    private void btnPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPdfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPdfActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRequest;
    private javax.swing.JButton btnPdf;
    private javax.swing.JButton btnRefesh;
    private javax.swing.JComboBox<String> cbRequestType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlRequest1;
    private javax.swing.JPanel pnlRequest2;
    private javax.swing.JPanel pnlRequestButton;
    private javax.swing.JTable tblRequets;
    private javax.swing.JTextField txtSearchRequest;
    // End of variables declaration//GEN-END:variables
}
