/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.pharmacy.app.GUI.Requests;

/**
 *
 * @author phong
 */
public class UpdateRequest extends javax.swing.JDialog {

    /**
     * Creates new form UpdateRequest
     */
    public UpdateRequest(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlRequest = new javax.swing.JPanel();
        lblRequest = new javax.swing.JLabel();
        pnlRequestFields = new javax.swing.JPanel();
        lblRequestType = new javax.swing.JLabel();
        txtRequestDate = new javax.swing.JTextField();
        cbRequestType = new javax.swing.JComboBox<>();
        lblRequestDate = new javax.swing.JLabel();
        lblLeaveStartDate = new javax.swing.JLabel();
        txtLeaveStartDate = new javax.swing.JTextField();
        lblLeaveEndDate = new javax.swing.JLabel();
        txtLeaveEndDate = new javax.swing.JTextField();
        lblReason = new javax.swing.JLabel();
        lblRequestID = new javax.swing.JLabel();
        txtRequestID = new javax.swing.JTextField();
        spReason = new javax.swing.JScrollPane();
        txtReason = new javax.swing.JTextArea();
        pnlButton = new javax.swing.JPanel();
        btnUpdateRequest = new javax.swing.JButton();
        btnDeleteRequest = new javax.swing.JButton();
        btnCancelRequest = new javax.swing.JButton();
        pnlApprovalInfo = new javax.swing.JPanel();
        lblStatus = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        lblResponseDate = new javax.swing.JLabel();
        txtResponseDate = new javax.swing.JTextField();
        lblComment = new javax.swing.JLabel();
        spComment = new javax.swing.JScrollPane();
        txtComment = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lblRequest.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRequest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRequest.setText("THÔNG TIN ĐƠN");
        pnlRequest.add(lblRequest);

        pnlRequestFields.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nội dung đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        pnlRequestFields.setLayout(new java.awt.GridBagLayout());

        lblRequestType.setText("Loại đơn:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 30, 20);
        pnlRequestFields.add(lblRequestType, gridBagConstraints);

        txtRequestDate.setText("Lấy ngày hiện tại");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 10.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 10);
        pnlRequestFields.add(txtRequestDate, gridBagConstraints);

        cbRequestType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đơn xin nghỉ phép", "Đơn xin nghỉ việc", "Đơn xin nghỉ ốm", "Đơn xin nghỉ thai sản" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 10.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 10);
        pnlRequestFields.add(cbRequestType, gridBagConstraints);

        lblRequestDate.setText("Ngày gửi đơn:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 30, 20);
        pnlRequestFields.add(lblRequestDate, gridBagConstraints);

        lblLeaveStartDate.setText("Ngày nghỉ:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 30, 20);
        pnlRequestFields.add(lblLeaveStartDate, gridBagConstraints);

        txtLeaveStartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLeaveStartDateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 10.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 10);
        pnlRequestFields.add(txtLeaveStartDate, gridBagConstraints);

        lblLeaveEndDate.setText("Ngày quay lại:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 30, 20);
        pnlRequestFields.add(lblLeaveEndDate, gridBagConstraints);

        txtLeaveEndDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLeaveEndDateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 10.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 10);
        pnlRequestFields.add(txtLeaveEndDate, gridBagConstraints);

        lblReason.setText("Lí do:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 20, 20);
        pnlRequestFields.add(lblReason, gridBagConstraints);

        lblRequestID.setText("Mã đơn:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 30, 20);
        pnlRequestFields.add(lblRequestID, gridBagConstraints);

        txtRequestID.setEditable(false);
        txtRequestID.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 10.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 30, 10);
        pnlRequestFields.add(txtRequestID, gridBagConstraints);

        spReason.setMinimumSize(new java.awt.Dimension(234, 86));

        txtReason.setColumns(20);
        txtReason.setRows(5);
        spReason.setViewportView(txtReason);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        pnlRequestFields.add(spReason, gridBagConstraints);

        pnlButton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 5));

        btnUpdateRequest.setBackground(new java.awt.Color(0, 204, 51));
        btnUpdateRequest.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdateRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateRequest.setText("Cập nhật");
        pnlButton.add(btnUpdateRequest);

        btnDeleteRequest.setBackground(new java.awt.Color(255, 0, 0));
        btnDeleteRequest.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeleteRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteRequest.setText("Xóa");
        pnlButton.add(btnDeleteRequest);

        btnCancelRequest.setBackground(new java.awt.Color(153, 153, 153));
        btnCancelRequest.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelRequest.setText("Hủy");
        pnlButton.add(btnCancelRequest);

        pnlApprovalInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin phê duyệt", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        pnlApprovalInfo.setLayout(new java.awt.GridBagLayout());

        lblStatus.setText("Trạng thái:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 30, 20);
        pnlApprovalInfo.add(lblStatus, gridBagConstraints);

        txtStatus.setEditable(false);
        txtStatus.setFocusable(false);
        txtStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStatusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 10.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 30, 10);
        pnlApprovalInfo.add(txtStatus, gridBagConstraints);

        lblResponseDate.setText("Ngày phản hồi:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 30, 20);
        pnlApprovalInfo.add(lblResponseDate, gridBagConstraints);

        txtResponseDate.setEditable(false);
        txtResponseDate.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 10.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 10);
        pnlApprovalInfo.add(txtResponseDate, gridBagConstraints);

        lblComment.setText("Ghi chú của quản lý:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 30, 20);
        pnlApprovalInfo.add(lblComment, gridBagConstraints);

        spComment.setMinimumSize(new java.awt.Dimension(234, 86));

        txtComment.setEditable(false);
        txtComment.setColumns(20);
        txtComment.setRows(5);
        txtComment.setFocusable(false);
        spComment.setViewportView(txtComment);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        pnlApprovalInfo.add(spComment, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlRequestFields, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(pnlApprovalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlRequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnlRequest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlRequestFields, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                    .addComponent(pnlApprovalInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(pnlButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLeaveStartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLeaveStartDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLeaveStartDateActionPerformed

    private void txtLeaveEndDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLeaveEndDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLeaveEndDateActionPerformed

    private void txtStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateRequest dialog = new UpdateRequest(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelRequest;
    private javax.swing.JButton btnDeleteRequest;
    private javax.swing.JButton btnUpdateRequest;
    private javax.swing.JComboBox<String> cbRequestType;
    private javax.swing.JLabel lblComment;
    private javax.swing.JLabel lblLeaveEndDate;
    private javax.swing.JLabel lblLeaveStartDate;
    private javax.swing.JLabel lblReason;
    private javax.swing.JLabel lblRequest;
    private javax.swing.JLabel lblRequestDate;
    private javax.swing.JLabel lblRequestID;
    private javax.swing.JLabel lblRequestType;
    private javax.swing.JLabel lblResponseDate;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPanel pnlApprovalInfo;
    private javax.swing.JPanel pnlButton;
    private javax.swing.JPanel pnlRequest;
    private javax.swing.JPanel pnlRequestFields;
    private javax.swing.JScrollPane spComment;
    private javax.swing.JScrollPane spReason;
    private javax.swing.JTextArea txtComment;
    private javax.swing.JTextField txtLeaveEndDate;
    private javax.swing.JTextField txtLeaveStartDate;
    private javax.swing.JTextArea txtReason;
    private javax.swing.JTextField txtRequestDate;
    private javax.swing.JTextField txtRequestID;
    private javax.swing.JTextField txtResponseDate;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
}
