/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pharmacy.app.GUI.Promo;
import com.pharmacy.app.DTO.Promotion;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Giai Cuu Li San
 */
public class HomePromo extends javax.swing.JPanel {
    private ArrayList<Promotion> promoList;
    /**
     * Creates new form HomePromo
     */
    public HomePromo() {
        initComponents();
        promoList = new ArrayList<>();
        loadPromoData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plHeader = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        plSearch = new javax.swing.JPanel();
        cbSort = new javax.swing.JComboBox<>();
        txtSearch1 = new javax.swing.JTextField();
        plButton = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnRefesh = new javax.swing.JButton();
        lblImg = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPromo = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(700, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setLayout(new java.awt.BorderLayout());

        plHeader.setBackground(new java.awt.Color(255, 255, 255));
        plHeader.setMaximumSize(new java.awt.Dimension(800, 100));
        plHeader.setMinimumSize(new java.awt.Dimension(800, 100));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("QUẢN LÝ MÃ KHUYẾN MÃI");

        plSearch.setBackground(new java.awt.Color(255, 255, 255));
        plSearch.setMaximumSize(new java.awt.Dimension(450, 70));
        plSearch.setMinimumSize(new java.awt.Dimension(450, 70));
        plSearch.setPreferredSize(new java.awt.Dimension(450, 70));
        plSearch.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 20));

        cbSort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbSort.setMinimumSize(new java.awt.Dimension(100, 30));
        cbSort.setPreferredSize(new java.awt.Dimension(100, 30));
        plSearch.add(cbSort);

        txtSearch1.setMaximumSize(new java.awt.Dimension(300, 30));
        txtSearch1.setMinimumSize(new java.awt.Dimension(300, 30));
        txtSearch1.setPreferredSize(new java.awt.Dimension(300, 30));
        plSearch.add(txtSearch1);

        plButton.setBackground(new java.awt.Color(255, 255, 255));
        plButton.setMaximumSize(new java.awt.Dimension(300, 70));
        plButton.setMinimumSize(new java.awt.Dimension(300, 70));
        plButton.setPreferredSize(new java.awt.Dimension(300, 70));
        plButton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 15));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.setMaximumSize(new java.awt.Dimension(75, 30));
        btnAdd.setMinimumSize(new java.awt.Dimension(75, 30));
        btnAdd.setPreferredSize(new java.awt.Dimension(75, 30));
        plButton.add(btnAdd);

        btnRefesh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRefesh.setText("Làm mới");
        btnRefesh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRefesh.setMaximumSize(new java.awt.Dimension(90, 30));
        btnRefesh.setMinimumSize(new java.awt.Dimension(90, 30));
        btnRefesh.setPreferredSize(new java.awt.Dimension(90, 30));
        plButton.add(btnRefesh);

        lblImg.setBackground(new java.awt.Color(255, 255, 255));
        lblImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pdf.png"))); // NOI18N
        plButton.add(lblImg);

        javax.swing.GroupLayout plHeaderLayout = new javax.swing.GroupLayout(plHeader);
        plHeader.setLayout(plHeaderLayout);
        plHeaderLayout.setHorizontalGroup(
            plHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plHeaderLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(plSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(plButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 423, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        plHeaderLayout.setVerticalGroup(
            plHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        add(plHeader, java.awt.BorderLayout.NORTH);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 650));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jSeparator1.setMaximumSize(new java.awt.Dimension(700, 10));
        jSeparator1.setMinimumSize(new java.awt.Dimension(700, 10));
        jSeparator1.setPreferredSize(new java.awt.Dimension(700, 10));
        jPanel1.add(jSeparator1, java.awt.BorderLayout.NORTH);

        jScrollPane2.setMinimumSize(new java.awt.Dimension(760, 510));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(1180, 620));

        tblPromo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblPromo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"KM01", "Sale Ngày Nhà Thuốc VN", null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã khuyến mãi", "Tên chương trình", "Loại khuyến mãi", "Ngày bắt đầu", "Ngày kết thúc"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblPromo.setEnabled(false);
        tblPromo.setMaximumSize(new java.awt.Dimension(700, 600));
        tblPromo.setMinimumSize(new java.awt.Dimension(700, 450));
        tblPromo.setPreferredSize(new java.awt.Dimension(1180, 600));
        tblPromo.setRowHeight(30);
        tblPromo.setShowGrid(true);
        tblPromo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPromoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPromo);

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tblPromoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPromoMouseClicked
        if (evt.getClickCount() == 2){
            int row = tblPromo.rowAtPoint(evt.getPoint());
            showPromoDetails(row);
        }
    }//GEN-LAST:event_tblPromoMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRefesh;
    private javax.swing.JComboBox<String> cbSort;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblImg;
    private javax.swing.JPanel plButton;
    private javax.swing.JPanel plHeader;
    private javax.swing.JPanel plSearch;
    private javax.swing.JTable tblPromo;
    private javax.swing.JTextField txtSearch1;
    // End of variables declaration//GEN-END:variables

    private void loadPromoData() {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        
        try {
            // Thêm dữ liệu khuyến mãi vào ArrayList
            promoList.add(new Promotion("KM01", "Sale Ngày Nhà Thuốc VN", "Điểm tích lũy", null, 
                                    null, 1000, 50.0, dateFormat.parse("2025-04-01"), dateFormat.parse("2025-04-10")));
            promoList.add(new Promotion("KM02", "Giảm Giá Ngày Quốc Tế", "Mặt hàng", "Thuốc XYZ", 
                                    15.0, null, null, dateFormat.parse("2025-05-01"), dateFormat.parse("2025-05-05")));
            promoList.add(new Promotion("KM03", "Khuyến Mãi Mùa Hè", "Điểm tích lũy", null, 
                                    null, 500, 25.0, dateFormat.parse("2025-06-01"), dateFormat.parse("2025-06-30")));
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        // Cập nhật bảng với dữ liệu khuyến mãi
        updateTable();
    }

    private void updateTable() {
                DefaultTableModel model = (DefaultTableModel) tblPromo.getModel();

        // Xóa các dòng cũ
        model.setRowCount(0);

        // Duyệt qua danh sách khuyến mãi và thêm dữ liệu vào bảng (chỉ 5 trường cần hiển thị)
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        
        for (Promotion promo : promoList) {
            model.addRow(new Object[]{
                promo.getPromotionId(),  // Mã khuyến mãi
                promo.getProgramName(),   // Tên chương trình khuyến mãi
                promo.getPromotionType(),       // Loại khuyến mãi
                dateFormat.format(promo.getStartDate()), // Ngày bắt đầu
                dateFormat.format(promo.getEndDate())    // Ngày kết thúc
            });
        }
    }

    private void showPromoDetails(int row) {
        Promotion promo = promoList.get(row);
        
        PromoDetail dialog = new PromoDetail((JFrame) SwingUtilities.getWindowAncestor(this), promo);
        dialog.setVisible(true);
        
        // Hiển thị thông tin chi tiết trong một dialog (JOptionPane)
//        String message = "Mã khuyến mãi: " + promo.getPromotionId() + "\n" +
//                         "Tên chương trình: " + promo.getProgramName() + "\n" +
//                         "Loại khuyến mãi: " + promo.getPromotionType() + "\n" +
//                         "Sản phẩm: " + promo.getProduct() + "\n" +
//                         "Phần trăm giảm giá: " + promo.getDiscountPercent() + "%\n" +
//                         "Điểm tích lũy tối thiểu: " + promo.getMinAccumulatedPoints() + "\n" +
//                         "Số tiền giảm: " + promo.getDiscountAmount() + "\n" +
//                         "Ngày bắt đầu: " + new SimpleDateFormat("yyyy-MM-dd").format(promo.getStartDate()) + "\n" +
//                         "Ngày kết thúc: " + new SimpleDateFormat("yyyy-MM-dd").format(promo.getEndDate());
//
//        // Hiển thị thông tin trong một dialog
//        JOptionPane.showMessageDialog(this, message, "Chi tiết khuyến mãi", JOptionPane.INFORMATION_MESSAGE);
    }
    
    
}
