/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pharmacy.app.GUI.Promo;
import com.pharmacy.app.BUS.PromotionBUS;
import com.pharmacy.app.DTO.PromotionDTO;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 
 * @author Giai Cuu Li San
 */
public class HomePromo extends javax.swing.JPanel{
    private PromotionBUS promoBUS = new PromotionBUS(); // Lớp xử lý nghiệp vụ cho Promo
    private ArrayList<PromotionDTO> promotionList = new ArrayList<>();
    private ArrayList<PromotionDTO> promotionListByType = new ArrayList<>();

    public HomePromo() {
        initComponents();
        setupTable();
        loadAllData();
        
        txtSearch.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                searchPromo();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                searchPromo();

            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                searchPromo();

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plHeader = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        plSearch = new javax.swing.JPanel();
        cbSort = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        plButton = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnRefesh = new javax.swing.JButton();
        lblImg = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPromo = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(700, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setLayout(new java.awt.BorderLayout());

        plHeader.setBackground(new java.awt.Color(255, 255, 255));
        plHeader.setMaximumSize(new java.awt.Dimension(800, 100));
        plHeader.setMinimumSize(new java.awt.Dimension(800, 100));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("QUẢN LÝ MÃ KHUYẾN MÃI");

        plSearch.setBackground(new java.awt.Color(255, 255, 255));
        plSearch.setMaximumSize(new java.awt.Dimension(450, 70));
        plSearch.setMinimumSize(new java.awt.Dimension(450, 70));
        plSearch.setPreferredSize(new java.awt.Dimension(450, 70));
        plSearch.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 20));

        cbSort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Đổi điểm", "Giảm phần trăm" }));
        cbSort.setMinimumSize(new java.awt.Dimension(100, 30));
        cbSort.setPreferredSize(new java.awt.Dimension(100, 30));
        cbSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSortActionPerformed(evt);
            }
        });
        plSearch.add(cbSort);

        txtSearch.setMaximumSize(new java.awt.Dimension(300, 30));
        txtSearch.setMinimumSize(new java.awt.Dimension(300, 30));
        txtSearch.setPreferredSize(new java.awt.Dimension(300, 30));
        plSearch.add(txtSearch);

        plButton.setBackground(new java.awt.Color(255, 255, 255));
        plButton.setMaximumSize(new java.awt.Dimension(300, 70));
        plButton.setMinimumSize(new java.awt.Dimension(300, 70));
        plButton.setPreferredSize(new java.awt.Dimension(300, 70));
        plButton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 15));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.setMaximumSize(new java.awt.Dimension(75, 30));
        btnAdd.setMinimumSize(new java.awt.Dimension(75, 30));
        btnAdd.setPreferredSize(new java.awt.Dimension(75, 30));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        plButton.add(btnAdd);

        btnRefesh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRefesh.setText("Làm mới");
        btnRefesh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRefesh.setMaximumSize(new java.awt.Dimension(90, 30));
        btnRefesh.setMinimumSize(new java.awt.Dimension(90, 30));
        btnRefesh.setPreferredSize(new java.awt.Dimension(90, 30));
        btnRefesh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefeshActionPerformed(evt);
            }
        });
        plButton.add(btnRefesh);

        lblImg.setBackground(new java.awt.Color(255, 255, 255));
        lblImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pdf.png"))); // NOI18N
        plButton.add(lblImg);

        javax.swing.GroupLayout plHeaderLayout = new javax.swing.GroupLayout(plHeader);
        plHeader.setLayout(plHeaderLayout);
        plHeaderLayout.setHorizontalGroup(
            plHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plHeaderLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(plSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(plButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 423, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        plHeaderLayout.setVerticalGroup(
            plHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        add(plHeader, java.awt.BorderLayout.NORTH);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 650));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jSeparator1.setMaximumSize(new java.awt.Dimension(700, 10));
        jSeparator1.setMinimumSize(new java.awt.Dimension(700, 10));
        jSeparator1.setPreferredSize(new java.awt.Dimension(700, 10));
        jPanel1.add(jSeparator1, java.awt.BorderLayout.NORTH);

        jScrollPane2.setMinimumSize(new java.awt.Dimension(760, 510));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(1180, 620));

        tblPromo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblPromo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"KM01", "Sale Ngày Nhà Thuốc VN", null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã khuyến mãi", "Tên chương trình", "Loại khuyến mãi", "Ngày bắt đầu", "Ngày kết thúc"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TableColumnModel columnModel = tblPromo.getColumnModel();

        columnModel.getColumn(0).setPreferredWidth(20);
        columnModel.getColumn(0).setPreferredWidth(50);
        columnModel.getColumn(0).setPreferredWidth(50);
        columnModel.getColumn(0).setPreferredWidth(50);
        columnModel.getColumn(0).setPreferredWidth(50);
        tblPromo.setEnabled(false);
        tblPromo.setMaximumSize(new java.awt.Dimension(700, 600));
        tblPromo.setMinimumSize(new java.awt.Dimension(700, 450));
        tblPromo.setPreferredSize(new java.awt.Dimension(1180, 600));
        tblPromo.setRowHeight(30);
        tblPromo.setShowGrid(true);
        tblPromo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPromoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPromo);

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tblPromoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPromoMouseClicked
        int row = tblPromo.rowAtPoint(evt.getPoint());
        if (row >= 0) {
            tblPromo.setRowSelectionInterval(row, row); // Tô màu dòng được click
        }
        if (evt.getClickCount() == 2){
            showPromoDetails(row);
        }
    }//GEN-LAST:event_tblPromoMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        AddPromo dialog = new AddPromo(this);
        dialog.setVisible(true); // Hiển thị cửa sổ chi tiết
    }//GEN-LAST:event_btnAddActionPerformed

    private void cbSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSortActionPerformed
        String selectedType = cbSort.getSelectedItem().toString();
        if (selectedType.equals("Tất cả")){
            loadAllData(); 
        } else {
            loadDataByType(selectedType);
        }
    }//GEN-LAST:event_cbSortActionPerformed

    private void btnRefeshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefeshActionPerformed
        cbSort.setSelectedItem("Tất cả");
        txtSearch.setText("");
        loadAllData();
    }//GEN-LAST:event_btnRefeshActionPerformed

    
    private void setupTable() {
        tblPromo.setSelectionBackground(new Color(0, 220, 230)); // Màu nền khi chọn (xanh nhạt)
        tblPromo.setSelectionForeground(Color.BLACK); // Màu chữ khi chọn
        tblPromo.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); // Chỉ cho phép chọn 1 dòng
    }
    
    // Dùng cho combobox

    
    // Dùng cho combobox
    public void loadDataByType(String type) {
        promotionListByType = promoBUS.getPromosByType(type); // Lấy danh sách mã giảm giá từ PromoBUS
        showDataToTable(promotionListByType);
    }

    public void showDataToTable(ArrayList<PromotionDTO> list) {
        DefaultTableModel model = (DefaultTableModel) tblPromo.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ

        for (PromotionDTO promo : list) {
            Object[] row = new Object[]{
                promo.getPromotionId(),
                promo.getProgramName(),
                promo.getPromotionType(),
                promo.getStartDate(),
                promo.getEndDate()
            };
            model.addRow(row);
        }
    }
    
    // Dùng cho
    public void loadAllData() {
        promotionList = promoBUS.getAllPromos();
        showDataToTable(promotionList);
    }


    private void showPromoDetails(int row) {
        if (row >= 0 && row < promotionList.size()) {
            String promoId = promotionList.get(row).getPromotionId();

            PromotionDTO promo = promoBUS.selectById(promoId);  // Lấy chi tiết từ DB

            if (promo != null) {
                PromoDetail dialog = new PromoDetail(this, promo);
                dialog.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy thông tin khuyến mãi.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Dữ liệu không hợp lệ.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    
    private void searchPromo() {
        String keyword = txtSearch.getText();
        ArrayList<PromotionDTO> result = promoBUS.searchAll(keyword);
        showDataToTable(result);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRefesh;
    private javax.swing.JComboBox<String> cbSort;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblImg;
    private javax.swing.JPanel plButton;
    private javax.swing.JPanel plHeader;
    private javax.swing.JPanel plSearch;
    private javax.swing.JTable tblPromo;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
