/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pharmacy.app;

import com.pharmacy.app.GUI.Authorization.AuthorizationManagement;
import com.pharmacy.app.GUI.Customer.CustomerList;
import com.pharmacy.app.GUI.Employee.EmployeeManagement;
import com.pharmacy.app.GUI.Employee.EmployeeProfile;
import com.pharmacy.app.GUI.Importing.Invoices;
import com.pharmacy.app.GUI.Importing.PurchaseOrder;
import com.pharmacy.app.GUI.Product.MedicalProducts;
import java.awt.*;
import javax.swing.*;
import com.pharmacy.app.GUI.Promo.*;
import com.pharmacy.app.GUI.Sales.HomeSales;
import com.pharmacy.app.GUI.Supplier.SupplierList;
import com.pharmacy.app.GUI.User.UserInfo;
import com.pharmacy.app.GUI.User.UserManagement;

/**
 *
 * @author LENOVO
 */
public class homepage extends javax.swing.JFrame {

    /**
     * Creates new form homapage
     */
    boolean a = true;
    private Color colorEntered = new Color(120,168,191);
    private Color colorExited = new Color(0,102,153);
    private CardLayout cardlayout = new CardLayout();
    private HomeSales homesales = new HomeSales();
    
    public homepage() {
        initComponents();
        this.setLocationRelativeTo(null);
        ContentPn.add(homesales, "Sales");
        switchToPanel("Sales");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderPn = new javax.swing.JPanel();
        iconExit = new javax.swing.JPanel();
        btnClose = new javax.swing.JPanel();
        closeicon = new javax.swing.JLabel();
        btnMax = new javax.swing.JPanel();
        minmaxicon = new javax.swing.JLabel();
        MenuPn = new javax.swing.JPanel();
        MenuIcon = new javax.swing.JPanel();
        btnBack = new javax.swing.JPanel();
        backicon = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnUser3 = new javax.swing.JPanel();
        usericon = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JPanel();
        logouticon = new javax.swing.JLabel();
        MenuHidePn = new javax.swing.JPanel();
        saleBtn = new javax.swing.JButton();
        productBtn = new javax.swing.JButton();
        cusBtn = new javax.swing.JButton();
        promoBtn = new javax.swing.JButton();
        infoBtn = new javax.swing.JButton();
        ContentPn = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        HeaderPn.setBackground(new java.awt.Color(0, 51, 102));
        HeaderPn.setPreferredSize(new java.awt.Dimension(1000, 45));
        HeaderPn.setLayout(new java.awt.BorderLayout());

        iconExit.setBackground(new java.awt.Color(0, 51, 102));
        iconExit.setMinimumSize(new java.awt.Dimension(150, 100));
        iconExit.setPreferredSize(new java.awt.Dimension(132, 120));
        iconExit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClose.setBackground(new java.awt.Color(0, 51, 102));
        btnClose.setMaximumSize(new java.awt.Dimension(45, 45));
        btnClose.setMinimumSize(new java.awt.Dimension(45, 45));
        btnClose.setPreferredSize(new java.awt.Dimension(45, 45));

        closeicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/closeWindow.png"))); // NOI18N
        closeicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeiconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeiconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeiconMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCloseLayout = new javax.swing.GroupLayout(btnClose);
        btnClose.setLayout(btnCloseLayout);
        btnCloseLayout.setHorizontalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCloseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeicon, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnCloseLayout.setVerticalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCloseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeicon, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        iconExit.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 45, 45));

        btnMax.setBackground(new java.awt.Color(0, 51, 102));
        btnMax.setMaximumSize(new java.awt.Dimension(45, 45));
        btnMax.setMinimumSize(new java.awt.Dimension(45, 45));
        btnMax.setPreferredSize(new java.awt.Dimension(45, 45));

        minmaxicon.setBackground(new java.awt.Color(0, 51, 102));
        minmaxicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxWindow.png"))); // NOI18N
        minmaxicon.setText("jLabel1");
        minmaxicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minmaxiconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minmaxiconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minmaxiconMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnMaxLayout = new javax.swing.GroupLayout(btnMax);
        btnMax.setLayout(btnMaxLayout);
        btnMaxLayout.setHorizontalGroup(
            btnMaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMaxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(minmaxicon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        btnMaxLayout.setVerticalGroup(
            btnMaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMaxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(minmaxicon)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        iconExit.add(btnMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 45));

        HeaderPn.add(iconExit, java.awt.BorderLayout.LINE_END);

        getContentPane().add(HeaderPn, java.awt.BorderLayout.PAGE_START);

        MenuPn.setPreferredSize(new java.awt.Dimension(250, 450));
        MenuPn.setLayout(new java.awt.BorderLayout());

        MenuIcon.setBackground(new java.awt.Color(0, 51, 102));
        MenuIcon.setMinimumSize(new java.awt.Dimension(400, 450));
        MenuIcon.setPreferredSize(new java.awt.Dimension(50, 450));
        MenuIcon.setLayout(new javax.swing.BoxLayout(MenuIcon, javax.swing.BoxLayout.Y_AXIS));

        btnBack.setBackground(new java.awt.Color(0, 51, 102));
        btnBack.setForeground(new java.awt.Color(0, 51, 102));
        btnBack.setMaximumSize(new java.awt.Dimension(50, 50));
        btnBack.setMinimumSize(new java.awt.Dimension(50, 50));

        backicon.setBackground(new java.awt.Color(204, 204, 204));
        backicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        backicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backiconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backiconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backiconMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnBackLayout = new javax.swing.GroupLayout(btnBack);
        btnBack.setLayout(btnBackLayout);
        btnBackLayout.setHorizontalGroup(
            btnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backicon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnBackLayout.setVerticalGroup(
            btnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backicon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        MenuIcon.add(btnBack);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );

        MenuIcon.add(jPanel1);

        btnUser3.setBackground(new java.awt.Color(0, 51, 102));
        btnUser3.setMaximumSize(new java.awt.Dimension(45, 45));
        btnUser3.setPreferredSize(new java.awt.Dimension(45, 45));

        usericon.setBackground(new java.awt.Color(0, 153, 153));
        usericon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        usericon.setPreferredSize(new java.awt.Dimension(31, 35));
        usericon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usericonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usericonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usericonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnUser3Layout = new javax.swing.GroupLayout(btnUser3);
        btnUser3.setLayout(btnUser3Layout);
        btnUser3Layout.setHorizontalGroup(
            btnUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usericon, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );
        btnUser3Layout.setVerticalGroup(
            btnUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnUser3Layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(usericon, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MenuIcon.add(btnUser3);

        logoutBtn.setBackground(new java.awt.Color(0, 51, 102));
        logoutBtn.setMaximumSize(new java.awt.Dimension(45, 45));
        logoutBtn.setPreferredSize(new java.awt.Dimension(45, 45));

        logouticon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        logouticon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logouticonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logouticonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout logoutBtnLayout = new javax.swing.GroupLayout(logoutBtn);
        logoutBtn.setLayout(logoutBtnLayout);
        logoutBtnLayout.setHorizontalGroup(
            logoutBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logouticon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        logoutBtnLayout.setVerticalGroup(
            logoutBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logouticon, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MenuIcon.add(logoutBtn);

        MenuPn.add(MenuIcon, java.awt.BorderLayout.LINE_START);

        MenuHidePn.setBackground(new java.awt.Color(0, 102, 153));
        MenuHidePn.setAutoscrolls(true);
        MenuHidePn.setMinimumSize(new java.awt.Dimension(200, 555));
        MenuHidePn.setPreferredSize(new java.awt.Dimension(200, 555));
        MenuHidePn.setVerifyInputWhenFocusTarget(false);
        MenuHidePn.setLayout(new java.awt.GridLayout(10, 1, 50, 10));

        saleBtn.setBackground(new java.awt.Color(0, 102, 153));
        saleBtn.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        saleBtn.setForeground(new java.awt.Color(255, 255, 255));
        saleBtn.setText("BÁN HÀNG");
        saleBtn.setBorder(null);
        saleBtn.setBorderPainted(false);
        saleBtn.setContentAreaFilled(false);
        saleBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saleBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saleBtn.setMaximumSize(new java.awt.Dimension(200, 50));
        saleBtn.setMinimumSize(new java.awt.Dimension(200, 50));
        saleBtn.setPreferredSize(new java.awt.Dimension(150, 30));
        saleBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                saleBtnMouseDragged(evt);
            }
        });
        saleBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saleBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saleBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saleBtnMouseExited(evt);
            }
        });
        saleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleBtnActionPerformed(evt);
            }
        });
        MenuHidePn.add(saleBtn);

        productBtn.setBackground(new java.awt.Color(0, 102, 153));
        productBtn.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        productBtn.setForeground(new java.awt.Color(255, 255, 255));
        productBtn.setText("QUẢN LÝ SẢN PHẨM");
        productBtn.setBorder(null);
        productBtn.setBorderPainted(false);
        productBtn.setContentAreaFilled(false);
        productBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        productBtn.setMaximumSize(new java.awt.Dimension(200, 30));
        productBtn.setMinimumSize(new java.awt.Dimension(200, 30));
        productBtn.setPreferredSize(new java.awt.Dimension(150, 30));
        productBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                productBtnMouseExited(evt);
            }
        });
        productBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productBtnActionPerformed(evt);
            }
        });
        MenuHidePn.add(productBtn);

        cusBtn.setBackground(new java.awt.Color(0, 102, 153));
        cusBtn.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        cusBtn.setForeground(new java.awt.Color(255, 255, 255));
        cusBtn.setText("QUẢN LÝ KHÁCH HÀNG");
        cusBtn.setBorder(null);
        cusBtn.setBorderPainted(false);
        cusBtn.setContentAreaFilled(false);
        cusBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cusBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cusBtn.setMaximumSize(new java.awt.Dimension(200, 30));
        cusBtn.setMinimumSize(new java.awt.Dimension(200, 30));
        cusBtn.setPreferredSize(new java.awt.Dimension(150, 30));
        cusBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cusBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cusBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cusBtnMouseExited(evt);
            }
        });
        cusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusBtnActionPerformed(evt);
            }
        });
        MenuHidePn.add(cusBtn);

        promoBtn.setBackground(new java.awt.Color(0, 102, 153));
        promoBtn.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        promoBtn.setForeground(new java.awt.Color(255, 255, 255));
        promoBtn.setText("QUẢN LÝ KHUYẾN MÃI");
        promoBtn.setBorder(null);
        promoBtn.setBorderPainted(false);
        promoBtn.setContentAreaFilled(false);
        promoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        promoBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        promoBtn.setMaximumSize(new java.awt.Dimension(200, 30));
        promoBtn.setMinimumSize(new java.awt.Dimension(200, 30));
        promoBtn.setPreferredSize(new java.awt.Dimension(150, 30));
        promoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                promoBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                promoBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                promoBtnMouseExited(evt);
            }
        });
        promoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promoBtnActionPerformed(evt);
            }
        });
        MenuHidePn.add(promoBtn);

        infoBtn.setBackground(new java.awt.Color(0, 102, 153));
        infoBtn.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        infoBtn.setForeground(new java.awt.Color(255, 255, 255));
        infoBtn.setText("THÔNG TIN CÁ NHÂN");
        infoBtn.setBorder(null);
        infoBtn.setBorderPainted(false);
        infoBtn.setContentAreaFilled(false);
        infoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        infoBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        infoBtn.setMaximumSize(new java.awt.Dimension(200, 30));
        infoBtn.setMinimumSize(new java.awt.Dimension(200, 30));
        infoBtn.setPreferredSize(new java.awt.Dimension(150, 30));
        infoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                infoBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                infoBtnMouseExited(evt);
            }
        });
        MenuHidePn.add(infoBtn);

        MenuPn.add(MenuHidePn, java.awt.BorderLayout.CENTER);

        getContentPane().add(MenuPn, java.awt.BorderLayout.LINE_START);

        ContentPn.setBackground(new java.awt.Color(255, 255, 255));
        ContentPn.setPreferredSize(new java.awt.Dimension(1000, 700));
        ContentPn.setLayout(new java.awt.CardLayout());
        getContentPane().add(ContentPn, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1000, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
// cardlayout
    public void switchToPanel(String panelName) {
        ContentPn.setLayout(cardlayout);
        cardlayout.show(ContentPn, panelName);
        ContentPn.revalidate();
        ContentPn.repaint();
    }
    
    public void hideshow(JPanel menushowhide, boolean dashboard, JLabel button){
        if(dashboard == true){
            menushowhide.setPreferredSize(new Dimension(250, menushowhide.getHeight()));
            changeimage(button, "/back.png");
        }
        else{
            menushowhide.setPreferredSize(new Dimension(50, menushowhide.getHeight()));
            changeimage(button, "/menu.png");
        }
    }
    
    public void changeimage(JLabel button, String resourcheimg){
        ImageIcon aimg = new ImageIcon(getClass().getResource(resourcheimg));
        button.setIcon(aimg);
    }
    
    private void closeiconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeiconMouseEntered
        btnClose.setBackground(new Color(227, 52, 67));
    }//GEN-LAST:event_closeiconMouseEntered

    private void closeiconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeiconMouseExited
        btnClose.setBackground(new Color(0,51,102));
    }//GEN-LAST:event_closeiconMouseExited

    private void closeiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeiconMouseClicked
        btnClose.setBackground(new Color(227, 52, 67));
        System.exit(0);
    }//GEN-LAST:event_closeiconMouseClicked

    private void minmaxiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minmaxiconMouseClicked
        btnMax.setBackground(new Color(81, 115, 150));
        if (this.getExtendedState() != homepage.MAXIMIZED_BOTH){
            this.setExtendedState(homepage.MAXIMIZED_BOTH);
            }
        else {
            this.setExtendedState(homepage.NORMAL);
        }
    }//GEN-LAST:event_minmaxiconMouseClicked

    private void minmaxiconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minmaxiconMouseEntered
        btnMax.setBackground(new Color(81, 115, 150));
    }//GEN-LAST:event_minmaxiconMouseEntered

    private void minmaxiconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minmaxiconMouseExited
        btnMax.setBackground(new Color(0,51,102));
    }//GEN-LAST:event_minmaxiconMouseExited

    private void saleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saleBtnActionPerformed
// Bán hàng
    private void saleBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleBtnMouseEntered
        saleBtn.setBackground(colorEntered);
        saleBtn.setOpaque(true);
        
    }//GEN-LAST:event_saleBtnMouseEntered

    private void saleBtnMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleBtnMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_saleBtnMouseDragged

    private void saleBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleBtnMouseExited
        saleBtn.setBackground(colorExited);
        saleBtn.setOpaque(true);
    }//GEN-LAST:event_saleBtnMouseExited

    private void saleBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleBtnMouseClicked
        ContentPn.add(homesales, "Sales");
        switchToPanel("Sales");
    }//GEN-LAST:event_saleBtnMouseClicked

    private void cusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusBtnActionPerformed

    private void cusBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cusBtnMouseExited
        cusBtn.setBackground(colorExited);
        cusBtn.setOpaque(true);
    }//GEN-LAST:event_cusBtnMouseExited

// Khách hàng
    private void cusBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cusBtnMouseEntered
        cusBtn.setBackground(colorEntered);
        cusBtn.setOpaque(true);
    }//GEN-LAST:event_cusBtnMouseEntered

    private void cusBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cusBtnMouseClicked
        ContentPn.add(new CustomerList(), "Customer");
        switchToPanel("Customer");
    }//GEN-LAST:event_cusBtnMouseClicked

    private void promoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_promoBtnActionPerformed

    private void promoBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_promoBtnMouseExited
        promoBtn.setBackground(colorExited);
        promoBtn.setOpaque(true);
    }//GEN-LAST:event_promoBtnMouseExited

// Khuyến mãi
    private void promoBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_promoBtnMouseEntered
        promoBtn.setBackground(colorEntered);
        promoBtn.setOpaque(true);
    }//GEN-LAST:event_promoBtnMouseEntered

    private void promoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_promoBtnMouseClicked
        ContentPn.add(new HomePromo(), "Promo");
        switchToPanel("Promo");
    }//GEN-LAST:event_promoBtnMouseClicked

    private void productBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productBtnActionPerformed

    private void productBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productBtnMouseExited
        productBtn.setBackground(colorExited);
        productBtn.setOpaque(true);
    }//GEN-LAST:event_productBtnMouseExited

// Sản phẩm
    private void productBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productBtnMouseEntered
        productBtn.setBackground(colorEntered);
        productBtn.setOpaque(true);
    }//GEN-LAST:event_productBtnMouseEntered

    private void productBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productBtnMouseClicked
        ContentPn.add(new MedicalProducts(), "Medinces");
        switchToPanel("Medinces");
    }//GEN-LAST:event_productBtnMouseClicked

    private void usericonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usericonMouseClicked
        UserInfo userDialog = new UserInfo((Frame)SwingUtilities.getWindowAncestor(usericon), true);
        userDialog.setLocationRelativeTo(null);
        userDialog.setVisible(true);
    }//GEN-LAST:event_usericonMouseClicked

    private void infoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoBtnMouseClicked
        ContentPn.add(new EmployeeProfile(), "Profile");
        switchToPanel("Profile");
    }//GEN-LAST:event_infoBtnMouseClicked

    private void infoBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoBtnMouseEntered
        infoBtn.setBackground(colorEntered);
        infoBtn.setOpaque(true);
    }//GEN-LAST:event_infoBtnMouseEntered

    private void infoBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoBtnMouseExited
        infoBtn.setBackground(colorExited);
        infoBtn.setOpaque(true);
    }//GEN-LAST:event_infoBtnMouseExited

    private void usericonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usericonMouseEntered
        usericon.setBackground(new Color(81, 115, 150));
    }//GEN-LAST:event_usericonMouseEntered

    private void usericonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usericonMouseExited
        usericon.setBackground(new Color(0,51,102));
    }//GEN-LAST:event_usericonMouseExited

    private void logouticonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logouticonMouseEntered
        logouticon.setBackground(new Color(81, 115, 150));
    }//GEN-LAST:event_logouticonMouseEntered

    private void logouticonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logouticonMouseExited
        logouticon.setBackground(new Color(0,51,102));
    }//GEN-LAST:event_logouticonMouseExited

    private void backiconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backiconMouseExited
        btnBack.setBackground(new Color(0,51,102));
    }//GEN-LAST:event_backiconMouseExited

    private void backiconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backiconMouseEntered
        btnBack.setBackground(new Color(81, 115, 150));
    }//GEN-LAST:event_backiconMouseEntered

    private void backiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backiconMouseClicked
        if(a==true){
            hideshow(MenuPn, a, backicon);
            SwingUtilities.updateComponentTreeUI(this);
            a=false;
        }
        else{
            hideshow(MenuPn, a, backicon);
            SwingUtilities.updateComponentTreeUI(this);
            a=true;
        }
    }//GEN-LAST:event_backiconMouseClicked

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
         SwingUtilities.invokeLater(() -> new homepage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContentPn;
    private javax.swing.JPanel HeaderPn;
    private javax.swing.JPanel MenuHidePn;
    private javax.swing.JPanel MenuIcon;
    private javax.swing.JPanel MenuPn;
    private javax.swing.JLabel backicon;
    private javax.swing.JPanel btnBack;
    private javax.swing.JPanel btnClose;
    private javax.swing.JPanel btnMax;
    private javax.swing.JPanel btnUser3;
    private javax.swing.JLabel closeicon;
    private javax.swing.JButton cusBtn;
    private javax.swing.JPanel iconExit;
    private javax.swing.JButton infoBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel logoutBtn;
    private javax.swing.JLabel logouticon;
    private javax.swing.JLabel minmaxicon;
    private javax.swing.JButton productBtn;
    private javax.swing.JButton promoBtn;
    private javax.swing.JButton saleBtn;
    private javax.swing.JLabel usericon;
    // End of variables declaration//GEN-END:variables
}
