/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pharmacy.app.GUI.Supplier;

import com.pharmacy.app.BUS.SupplierBUS;
import com.pharmacy.app.DTO.SupplierDTO;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BOI QUAN
 */
public class SupplierList extends javax.swing.JPanel {

    /**
     * Creates new form SupplierList
     */
    public SupplierList() {
        initComponents();
        loadSupplierList();

    }
    
    
    private void loadSupplierList(){
        SupplierBUS supplierBUS = new SupplierBUS();
        List<SupplierDTO> suppliersList = supplierBUS.getAllSuppliers();

        DefaultTableModel model = (DefaultTableModel) tbSupplierList.getModel();
        model.setRowCount(0);
        
        for (SupplierDTO s: suppliersList){
            model.addRow(new Object[]{
                s.getId(),
                s.getName(),
                s.getPhone(),
                s.getAddress()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        plSearch = new javax.swing.JPanel();
        cbSort = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnRefesh = new javax.swing.JButton();
        lblImg = new javax.swing.JLabel();
        plSupplierList = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSupplierList = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(800, 580));
        setMinimumSize(new java.awt.Dimension(800, 580));
        setPreferredSize(new java.awt.Dimension(800, 580));
        setLayout(new java.awt.BorderLayout());

        plHeader.setBackground(new java.awt.Color(255, 255, 255));
        plHeader.setMaximumSize(new java.awt.Dimension(800, 100));
        plHeader.setMinimumSize(new java.awt.Dimension(800, 100));
        plHeader.setPreferredSize(new java.awt.Dimension(800, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ NHÀ CUNG CẤP");

        plSearch.setBackground(new java.awt.Color(255, 255, 255));
        plSearch.setMaximumSize(new java.awt.Dimension(450, 70));
        plSearch.setMinimumSize(new java.awt.Dimension(450, 70));
        plSearch.setPreferredSize(new java.awt.Dimension(450, 70));
        plSearch.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 20));

        cbSort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbSort.setMinimumSize(new java.awt.Dimension(100, 30));
        cbSort.setPreferredSize(new java.awt.Dimension(100, 30));
        plSearch.add(cbSort);

        txtSearch.setMaximumSize(new java.awt.Dimension(300, 30));
        txtSearch.setMinimumSize(new java.awt.Dimension(300, 30));
        txtSearch.setPreferredSize(new java.awt.Dimension(300, 30));
        plSearch.add(txtSearch);

        btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.setMaximumSize(new java.awt.Dimension(75, 30));
        btnAdd.setMinimumSize(new java.awt.Dimension(75, 30));
        btnAdd.setPreferredSize(new java.awt.Dimension(75, 30));
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        plSearch.add(btnAdd);

        btnRefesh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRefesh.setText("Làm mới");
        btnRefesh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRefesh.setMaximumSize(new java.awt.Dimension(90, 30));
        btnRefesh.setMinimumSize(new java.awt.Dimension(90, 30));
        btnRefesh.setPreferredSize(new java.awt.Dimension(90, 30));
        plSearch.add(btnRefesh);

        lblImg.setBackground(new java.awt.Color(255, 255, 255));
        lblImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pdf.png"))); // NOI18N
        plSearch.add(lblImg);

        javax.swing.GroupLayout plHeaderLayout = new javax.swing.GroupLayout(plHeader);
        plHeader.setLayout(plHeaderLayout);
        plHeaderLayout.setHorizontalGroup(
            plHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(plSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
        );
        plHeaderLayout.setVerticalGroup(
            plHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(plSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        add(plHeader, java.awt.BorderLayout.NORTH);

        plSupplierList.setBackground(new java.awt.Color(255, 255, 255));
        plSupplierList.setMaximumSize(new java.awt.Dimension(800, 450));
        plSupplierList.setMinimumSize(new java.awt.Dimension(800, 450));
        plSupplierList.setPreferredSize(new java.awt.Dimension(800, 450));
        plSupplierList.setLayout(new java.awt.BorderLayout());

        jSeparator1.setMaximumSize(new java.awt.Dimension(700, 10));
        jSeparator1.setMinimumSize(new java.awt.Dimension(700, 10));
        jSeparator1.setPreferredSize(new java.awt.Dimension(700, 10));
        plSupplierList.add(jSeparator1, java.awt.BorderLayout.NORTH);

        jScrollPane1.setMaximumSize(new java.awt.Dimension(780, 400));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(780, 400));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(780, 400));

        tbSupplierList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"NCC1", "Công ty TNHH ABC", "0123456789", "123 Đường 18 P2 Q6 TP.HCM"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MÃ NCC", "TÊN NCC", "SỐ ĐIỆN THOẠI", "ĐỊA CHỈ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbSupplierList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbSupplierList.setGridColor(new java.awt.Color(211, 211, 211));
        tbSupplierList.setMaximumSize(new java.awt.Dimension(700, 400));
        tbSupplierList.setMinimumSize(new java.awt.Dimension(700, 400));
        tbSupplierList.setName(""); // NOI18N
        tbSupplierList.setPreferredSize(new java.awt.Dimension(700, 400));
        tbSupplierList.setSelectionBackground(new java.awt.Color(51, 51, 51));
        tbSupplierList.setShowGrid(true);
        jScrollPane1.setViewportView(tbSupplierList);

        plSupplierList.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(plSupplierList, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        AddSupplier addDialog = new AddSupplier((JFrame) SwingUtilities.getWindowAncestor(this), true);
        addDialog.setLocationRelativeTo(null);
        addDialog.setVisible(true);
    }//GEN-LAST:event_btnAddMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRefesh;
    private javax.swing.JComboBox<String> cbSort;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblImg;
    private javax.swing.JPanel plHeader;
    private javax.swing.JPanel plSearch;
    private javax.swing.JPanel plSupplierList;
    private javax.swing.JTable tbSupplierList;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
