/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pharmacy.app.GUI.Supplier;

import com.pharmacy.app.BUS.SupplierBUS;
import com.pharmacy.app.DTO.SupplierDTO;
import com.pharmacy.app.DAO.SupplierDAO;
import com.pharmacy.app.utils.ExportPDF;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author BOI QUAN
 */
public final class SupplierList extends javax.swing.JPanel {
    private SupplierBUS supplierBUS;
    private SupplierDAO supplierDAO;
    /**
     * Creates new form SupplierList
     */
    public SupplierList() {
        initComponents();
        initBUS();
        setupListeners();
        loadSupplierData();
    }
    
    private void initBUS(){
        supplierBUS = new SupplierBUS();
        supplierBUS.loadSupplierList();
    }
    
    private void setupListeners(){
        txtSearch.addFocusListener(new FocusAdapter(){
            @Override
            public void focusGained(FocusEvent e) {
                if (txtSearch.getText().equals("Tìm kiếm")) {
                    txtSearch.setText("");
                    txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 12));
                    txtSearch.setForeground(new java.awt.Color(0, 0, 0));
                }
            }
            @Override
            public void focusLost(FocusEvent e) {
                if (txtSearch.getText().isEmpty()) {
                    txtSearch.setText("Tìm kiếm");
                    txtSearch.setFont(new java.awt.Font("Segoe UI", 2, 12));
                    txtSearch.setForeground(new java.awt.Color(153, 153, 153));
                }
            }
        });
        // Setup search text field key listener
        txtSearch.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                String keyword = txtSearch.getText();
                if (!keyword.equals("Tìm kiếm")) {
                    searchSupplier(keyword);
                }
            }
        });
    }

    private void displayList(List<SupplierDTO> suppliersList) {
        DefaultTableModel model = (DefaultTableModel) tbSupplierList.getModel();
        model.setRowCount(0);

        for (SupplierDTO s: suppliersList){
            model.addRow(new Object[]{
                s.getId(),
                s.getName(),
                s.getPhone(),
                s.getEmail(),
                s.getAddress()
            });
        }
    }

    public void loadSupplierData(){
        List<SupplierDTO> suppliersList = supplierBUS.getAllSuppliers();
        displayList(suppliersList);
    }
    
    private void searchSupplier(String keyword){
        if (keyword.isEmpty() || keyword.equals("Tìm kiếm")) {
            loadSupplierData(); // Hiển thị lại toàn bộ nếu người dùng xóa từ khóa
            return;
        }
        
        List<SupplierDTO> searchResult = supplierBUS.search(keyword);
        displayList(searchResult);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        plSearch = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnRefesh = new javax.swing.JButton();
        btnExportPDF = new javax.swing.JButton();
        plSupplierList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSupplierList = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(326589, 326589));
        setMinimumSize(new java.awt.Dimension(800, 580));
        setPreferredSize(new java.awt.Dimension(1200, 700));
        setLayout(new java.awt.BorderLayout(0, 10));

        plHeader.setBackground(new java.awt.Color(255, 255, 255));
        plHeader.setMaximumSize(new java.awt.Dimension(3265689, 326589));
        plHeader.setMinimumSize(new java.awt.Dimension(800, 100));
        plHeader.setPreferredSize(new java.awt.Dimension(800, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ NHÀ CUNG CẤP");

        plSearch.setBackground(new java.awt.Color(255, 255, 255));
        plSearch.setMaximumSize(new java.awt.Dimension(450, 70));
        plSearch.setMinimumSize(new java.awt.Dimension(450, 70));
        plSearch.setPreferredSize(new java.awt.Dimension(450, 70));
        plSearch.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 20));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        txtSearch.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(153, 153, 153));
        txtSearch.setText("Tìm kiếm");
        txtSearch.setToolTipText("");
        txtSearch.setMaximumSize(new java.awt.Dimension(325689, 30));
        txtSearch.setMinimumSize(new java.awt.Dimension(300, 30));
        txtSearch.setPreferredSize(new java.awt.Dimension(600, 30));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        jPanel1.add(txtSearch);

        plSearch.add(jPanel1);

        btnAdd.setBackground(new java.awt.Color(0, 204, 51));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Thêm");
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.setMaximumSize(new java.awt.Dimension(75, 30));
        btnAdd.setMinimumSize(new java.awt.Dimension(75, 30));
        btnAdd.setPreferredSize(new java.awt.Dimension(75, 30));
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        plSearch.add(btnAdd);

        btnRefesh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRefesh.setText("Tải lại");
        btnRefesh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRefesh.setMaximumSize(new java.awt.Dimension(90, 30));
        btnRefesh.setMinimumSize(new java.awt.Dimension(90, 30));
        btnRefesh.setPreferredSize(new java.awt.Dimension(90, 30));
        btnRefesh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefeshActionPerformed(evt);
            }
        });
        plSearch.add(btnRefesh);

        btnExportPDF.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnExportPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pdf.png"))); // NOI18N
        btnExportPDF.setText("Xuất PDF");
        btnExportPDF.setAlignmentX(0.5F);
        btnExportPDF.setBorder(null);
        btnExportPDF.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExportPDF.setPreferredSize(new java.awt.Dimension(46, 40));
        btnExportPDF.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExportPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportPDFActionPerformed(evt);
            }
        });
        plSearch.add(btnExportPDF);

        javax.swing.GroupLayout plHeaderLayout = new javax.swing.GroupLayout(plHeader);
        plHeader.setLayout(plHeaderLayout);
        plHeaderLayout.setHorizontalGroup(
            plHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(plSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 956, Short.MAX_VALUE)
        );
        plHeaderLayout.setVerticalGroup(
            plHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(plSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        add(plHeader, java.awt.BorderLayout.NORTH);

        plSupplierList.setBackground(new java.awt.Color(255, 255, 255));
        plSupplierList.setMaximumSize(new java.awt.Dimension(326589, 326589));
        plSupplierList.setMinimumSize(new java.awt.Dimension(800, 550));
        plSupplierList.setPreferredSize(new java.awt.Dimension(1160, 550));
        plSupplierList.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setMaximumSize(new java.awt.Dimension(326589, 326589));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(780, 400));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1180, 550));

        tbSupplierList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"NCC1", "Công ty TNHH ABC", "0123456789", null, "123 Đường 18 P2 Q6 TP.HCM"},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MÃ NCC", "TÊN NCC", "SỐ ĐIỆN THOẠI", "EMAIL", "ĐỊA CHỈ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbSupplierList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbSupplierList.setFocusable(false);
        tbSupplierList.setGridColor(new java.awt.Color(211, 211, 211));
        tbSupplierList.setMaximumSize(new java.awt.Dimension(326589, 326589));
        tbSupplierList.setMinimumSize(new java.awt.Dimension(700, 400));
        tbSupplierList.setName(""); // NOI18N
        tbSupplierList.setPreferredSize(new java.awt.Dimension(1180, 550));
        tbSupplierList.setSelectionBackground(new java.awt.Color(51, 51, 51));
        tbSupplierList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbSupplierList.setShowGrid(true);
        tbSupplierList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSupplierListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbSupplierList);
        tbSupplierList.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tbSupplierList.getColumnModel().getColumnCount() > 0) {
            tbSupplierList.getColumnModel().getColumn(0).setPreferredWidth(10);
            tbSupplierList.getColumnModel().getColumn(1).setPreferredWidth(50);
            tbSupplierList.getColumnModel().getColumn(2).setPreferredWidth(10);
            tbSupplierList.getColumnModel().getColumn(3).setPreferredWidth(30);
            tbSupplierList.getColumnModel().getColumn(4).setPreferredWidth(100);
        }

        plSupplierList.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(plSupplierList, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        AddSupplier addDialog = new AddSupplier((JFrame) SwingUtilities.getWindowAncestor(this), true);
        addDialog.setLocationRelativeTo(null);
        addDialog.setVisible(true);
    }//GEN-LAST:event_btnAddMouseClicked

    private void tbSupplierListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSupplierListMouseClicked
        int selectedRow = tbSupplierList.getSelectedRow();
        if (selectedRow != -1){
            // Lấy dữ liệu từ các cột trong dòng được chọn
            String id = tbSupplierList.getValueAt(selectedRow, 0).toString();
            // Tạo đối tượng SupplierDTO từ dữ liệu đã lấy
            SupplierDTO selectedSupplier = supplierBUS.getSupplierByID(id);
            
            SupplierDetail detailDialog = new SupplierDetail((JFrame) SwingUtilities.getWindowAncestor(this), true, selectedSupplier);
            detailDialog.setLocationRelativeTo(null);
            detailDialog.setVisible(true);
        }
    }//GEN-LAST:event_tbSupplierListMouseClicked

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:        
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnRefeshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefeshActionPerformed
        txtSearch.setText("Tìm kiếm");
        txtSearch.setForeground(new java.awt.Color(153, 153, 153));
        supplierBUS.loadSupplierList();
        loadSupplierData();
    }//GEN-LAST:event_btnRefeshActionPerformed

    private void btnExportPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportPDFActionPerformed
        // TODO add your handling code here:
        List<SupplierDTO> supplierList = supplierBUS.getAllSuppliers();
//        String[] headers = {"ID", "Tên công ty", "Số điện thoại", "Email", "Địa chỉ", "Còn hoạt động"};
//        ExportPDF.exportListToPDF(supplierList, "SupplierList.pdf", headers);
//        List<SupplierDTO> list = SupplierDAO.selectAll();
        String[] headers = {"Mã nhà cung cấp", "Tên nhà cung cấp", "SĐT", "Email", "Địa chỉ"};
        String[] fields = {"id", "name", "phone", "email", "address"};

        ExportPDF pdf = new ExportPDF();
        pdf.exportListToPDFWithDialog("DanhSachNhaCungCap", supplierList, headers, fields);

    }//GEN-LAST:event_btnExportPDFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnExportPDF;
    private javax.swing.JButton btnRefesh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel plHeader;
    private javax.swing.JPanel plSearch;
    private javax.swing.JPanel plSupplierList;
    private javax.swing.JTable tbSupplierList;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
