/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pharmacy.app.GUI.WorkSchedule;

/**
 *
 * @author phong
 */
public class WorkScheduleManagement extends javax.swing.JPanel {

    /**
     * Creates new form WorkScheduleManagement
     */
    public WorkScheduleManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlSchedule = new javax.swing.JPanel();
        pnlCreateSchedule = new javax.swing.JPanel();
        lblWeekPicker = new javax.swing.JLabel();
        cbWeekPicker = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        pnlWeekSchedule = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblWeekSchedule = new javax.swing.JTable();
        pnlAttendance = new javax.swing.JPanel();
        pnlEmployeeAttendance = new javax.swing.JPanel();
        lblWeekPicker1 = new javax.swing.JLabel();
        cbWeekPicker1 = new javax.swing.JComboBox<>();
        pnlWeekAttendance = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblWeekAttendance = new javax.swing.JTable();
        pnlWorkShift = new javax.swing.JPanel();
        pnlButton = new javax.swing.JPanel();
        btnAddPermission = new javax.swing.JButton();
        btnRefeshRole1 = new javax.swing.JButton();
        btnPdf1 = new javax.swing.JButton();
        pnlShiftList = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblShiftList = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        pnlSchedule.setBackground(new java.awt.Color(255, 255, 255));
        pnlSchedule.setLayout(new java.awt.BorderLayout());

        pnlCreateSchedule.setBackground(new java.awt.Color(255, 255, 255));
        pnlCreateSchedule.setPreferredSize(new java.awt.Dimension(464, 50));
        pnlCreateSchedule.setLayout(new java.awt.GridBagLayout());

        lblWeekPicker.setText("Chọn tuần:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        pnlCreateSchedule.add(lblWeekPicker, gridBagConstraints);

        cbWeekPicker.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "07/04/2025 - 13/04/2025", "14/04/2025 - 20/04/2025" }));
        cbWeekPicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbWeekPickerActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 3.0;
        pnlCreateSchedule.add(cbWeekPicker, gridBagConstraints);

        btnSave.setText("Lưu lịch");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 30);
        pnlCreateSchedule.add(btnSave, gridBagConstraints);

        jButton1.setText("Xóa");
        pnlCreateSchedule.add(jButton1, new java.awt.GridBagConstraints());

        pnlSchedule.add(pnlCreateSchedule, java.awt.BorderLayout.NORTH);

        pnlWeekSchedule.setBackground(new java.awt.Color(255, 255, 255));
        pnlWeekSchedule.setPreferredSize(new java.awt.Dimension(650, 450));
        pnlWeekSchedule.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(550, 402));

        tblWeekSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"UP", "Ca 1", null, "Ca 2", null, null, null, null},
                {"ABC", "Ca 2", "Ca 1", null, null, null, null, null},
                {"Cho cbbox chọn ca", null, null, null, null, null, null, null},
                {"hoặc cho ghi giờ ", null, null, null, null, null, null, null}
            },
            new String [] {
                "Nhân viên", "Thứ 2", "Thứ 3", "Thứ 4", "Thứ 5", "Thứ 6", "Thứ 7", "Chủ nhật"
            }
        ));
        tblWeekSchedule.setPreferredSize(new java.awt.Dimension(690, 80));
        jScrollPane1.setViewportView(tblWeekSchedule);
        if (tblWeekSchedule.getColumnModel().getColumnCount() > 0) {
            tblWeekSchedule.getColumnModel().getColumn(0).setPreferredWidth(150);
        }

        pnlWeekSchedule.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnlSchedule.add(pnlWeekSchedule, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Lịch làm việc", pnlSchedule);

        pnlAttendance.setBackground(new java.awt.Color(255, 255, 255));
        pnlAttendance.setLayout(new java.awt.BorderLayout());

        pnlEmployeeAttendance.setBackground(new java.awt.Color(255, 255, 255));
        pnlEmployeeAttendance.setPreferredSize(new java.awt.Dimension(240, 50));
        pnlEmployeeAttendance.setLayout(new java.awt.GridBagLayout());

        lblWeekPicker1.setText("Chọn tuần:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        pnlEmployeeAttendance.add(lblWeekPicker1, gridBagConstraints);

        cbWeekPicker1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "07/04/2025 - 13/04/2025", "14/04/2025 - 20/04/2025" }));
        cbWeekPicker1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbWeekPicker1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 3.0;
        pnlEmployeeAttendance.add(cbWeekPicker1, gridBagConstraints);

        pnlAttendance.add(pnlEmployeeAttendance, java.awt.BorderLayout.NORTH);

        pnlWeekAttendance.setBackground(new java.awt.Color(255, 255, 255));
        pnlWeekAttendance.setPreferredSize(new java.awt.Dimension(650, 450));
        pnlWeekAttendance.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setPreferredSize(new java.awt.Dimension(550, 402));

        tblWeekAttendance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"UP", "6:00 - 12:01", null, "13:21 - 18:00", null, null, null, null}
            },
            new String [] {
                "Nhân viên", "Thứ 2", "Thứ 3", "Thứ 4", "Thứ 5", "Thứ 6", "Thứ 7", "Chủ nhật"
            }
        ));
        tblWeekAttendance.setPreferredSize(new java.awt.Dimension(690, 80));
        jScrollPane2.setViewportView(tblWeekAttendance);
        if (tblWeekAttendance.getColumnModel().getColumnCount() > 0) {
            tblWeekAttendance.getColumnModel().getColumn(0).setPreferredWidth(150);
        }

        pnlWeekAttendance.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pnlAttendance.add(pnlWeekAttendance, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Chấm công", pnlAttendance);

        pnlWorkShift.setBackground(new java.awt.Color(255, 255, 255));
        pnlWorkShift.setLayout(new java.awt.BorderLayout());

        pnlButton.setBackground(new java.awt.Color(255, 255, 255));
        pnlButton.setPreferredSize(new java.awt.Dimension(320, 35));
        pnlButton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 5));

        btnAddPermission.setText("Thêm");
        btnAddPermission.setFocusable(false);
        btnAddPermission.setMaximumSize(new java.awt.Dimension(72, 22));
        btnAddPermission.setMinimumSize(new java.awt.Dimension(72, 22));
        btnAddPermission.setPreferredSize(new java.awt.Dimension(72, 22));
        pnlButton.add(btnAddPermission);

        btnRefeshRole1.setText("Tải lại");
        btnRefeshRole1.setFocusable(false);
        btnRefeshRole1.setMaximumSize(new java.awt.Dimension(72, 22));
        btnRefeshRole1.setMinimumSize(new java.awt.Dimension(72, 22));
        btnRefeshRole1.setPreferredSize(new java.awt.Dimension(72, 22));
        pnlButton.add(btnRefeshRole1);

        btnPdf1.setText("In PDF");
        btnPdf1.setFocusable(false);
        btnPdf1.setMaximumSize(new java.awt.Dimension(72, 22));
        btnPdf1.setMinimumSize(new java.awt.Dimension(72, 22));
        btnPdf1.setPreferredSize(new java.awt.Dimension(72, 22));
        pnlButton.add(btnPdf1);

        pnlWorkShift.add(pnlButton, java.awt.BorderLayout.NORTH);

        pnlShiftList.setBackground(new java.awt.Color(255, 255, 255));
        pnlShiftList.setPreferredSize(new java.awt.Dimension(600, 439));

        jScrollPane3.setPreferredSize(new java.awt.Dimension(580, 402));

        tblShiftList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã ca làm việc", "Giờ bắt đầu", "Giờ kết thúc"
            }
        ));
        tblShiftList.setFocusable(false);
        tblShiftList.setMinimumSize(new java.awt.Dimension(500, 80));
        tblShiftList.setPreferredSize(new java.awt.Dimension(500, 80));
        tblShiftList.setShowGrid(true);
        jScrollPane3.setViewportView(tblShiftList);

        javax.swing.GroupLayout pnlShiftListLayout = new javax.swing.GroupLayout(pnlShiftList);
        pnlShiftList.setLayout(pnlShiftListLayout);
        pnlShiftListLayout.setHorizontalGroup(
            pnlShiftListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
        );
        pnlShiftListLayout.setVerticalGroup(
            pnlShiftListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
        );

        pnlWorkShift.add(pnlShiftList, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Ca làm việc", pnlWorkShift);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void cbWeekPickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbWeekPickerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbWeekPickerActionPerformed

    private void cbWeekPicker1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbWeekPicker1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbWeekPicker1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPermission;
    private javax.swing.JButton btnPdf1;
    private javax.swing.JButton btnRefeshRole1;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbWeekPicker;
    private javax.swing.JComboBox<String> cbWeekPicker1;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblWeekPicker;
    private javax.swing.JLabel lblWeekPicker1;
    private javax.swing.JPanel pnlAttendance;
    private javax.swing.JPanel pnlButton;
    private javax.swing.JPanel pnlCreateSchedule;
    private javax.swing.JPanel pnlEmployeeAttendance;
    private javax.swing.JPanel pnlSchedule;
    private javax.swing.JPanel pnlShiftList;
    private javax.swing.JPanel pnlWeekAttendance;
    private javax.swing.JPanel pnlWeekSchedule;
    private javax.swing.JPanel pnlWorkShift;
    private javax.swing.JTable tblShiftList;
    private javax.swing.JTable tblWeekAttendance;
    private javax.swing.JTable tblWeekSchedule;
    // End of variables declaration//GEN-END:variables
}
